In [11]:
from urllib.request import urlopen, Request
from bs4 import BeautifulSoup

In [32]:
def getPageLink(num):
    assert num >= 0
    baseUrl ='https://tech.eu/news/'
    if num == 0 or num == 1:
        return baseUrl
    else:
        return f'{baseUrl}page/{num}/'
    

In [85]:
def getBSoup(url):
    req = Request(url, headers={'User-agent' : 'Mozilla/5.0'})
    page = urlopen(req).read().decode('utf8','ignore')
    soup = BeautifulSoup(page,'lxml')
    return soup

In [86]:
def getContent(url):
    #url = 'https://tech.eu/brief/bitmovin-20-million-financing-eib-video/'
    soup = getBSoup(url)
    ps = soup.find('div',class_='entry-content').select('p')
    text = ' '.join(map(lambda p: p.text, ps))
    return text

In [206]:
def getTechEUPosts():
    pagesToScrape = 20
    links = []
    posts = []
    for pageIndex in range(1,pagesToScrape+1):
        url = getPageLink(pageIndex)
        #print(url)
        soup = getBSoup(url)
        pageLinks = soup.find('div',{'role':'main'}).select('header h3 a')
        for pageLink in pageLinks:
            try:
                url = pageLink['href']
                title = pageLink.string.lower()
                str = 'tech stories this week'
                if str in title:
                    continue
                if not url.startswith('https://tech.eu/brief/'):
                    continue
                #print (url)
                posts.append(getContent(url))
                links.append(url)
            except:
                print('Exception occured')
    return posts, links


In [20]:
articleURL = 'https://tech.eu/news/'
req = Request(articleURL, headers={'User-agent' : 'Mozilla/5.0'})
page = urlopen(req).read().decode('utf8','ignore')
soup = BeautifulSoup(page,'lxml')
pageLinks = soup.find('div',{'role':'main'}).select('header h3 a')
pageLinks

[<a href="https://tech.eu/brief/these-were-the-10-biggest-european-tech-stories-this-week-15-november-2019/">These were the 10 biggest European tech stories this week</a>,
 <a href="https://tech.eu/brief/siren-scores-10-million-series-a-for-its-investigative-intelligence-platform-and-new-deep-tech-extension/">Siren scores $10 million Series A for its investigative intelligence platform and new deep tech extension</a>,
 <a href="https://tech.eu/brief/german-proptech-thing-it-collects-e4-2-million-to-expand-its-operating-system-for-smart-buildings/">German proptech Thing-it collects €4.2 million to expand its operating system for smart buildings</a>,
 <a href="https://tech.eu/brief/glue-raises-3-5-million-vr-collaboration-platform/">Glue raises €3.5 million for its immersive VR collaboration platform, bringing colleagues together in virtual spaces</a>,
 <a href="https://tech.eu/brief/snowplow-analytics-4-million-opensource-data-collection/">Snowplow Analytics raises £4 million to fuel it

In [28]:
for pageLink in pageLinks:
        url = pageLink['href']
        title = pageLink.string.lower()
        str = 'tech stories this week'
        if str in title:
            continue
        print (title)

siren scores $10 million series a for its investigative intelligence platform and new deep tech extension
german proptech thing-it collects €4.2 million to expand its operating system for smart buildings
glue raises €3.5 million for its immersive vr collaboration platform, bringing colleagues together in virtual spaces
snowplow analytics raises £4 million to fuel its open-source data collection platform
israeli proptech shapedo gets $650,000 from goldacre after finishing new relab accelerator programme
eqt ventures closes second fund at €660 million, will help startups scale out of europe and us companies scale in


In [49]:
pagesToScrape = 2
for pageIndex in range(1,pagesToScrape+1):
    url = getPageLink(pageIndex)
    #print(url)
    req = Request(articleURL, headers={'User-agent' : 'Mozilla/5.0'})
    page = urlopen(req).read().decode('utf8','ignore')
    soup = BeautifulSoup(page,'lxml')
    pageLinks = soup.find('div',{'role':'main'}).select('header h3 a')
    for pageLink in pageLinks:
        try:
            url = pageLink['href']
            title = pageLink.string.lower()
            str = 'tech stories this week'
            if str in title:
                continue
            print (url)
        except:
            print('Exception occured')
        

https://tech.eu/brief/siren-scores-10-million-series-a-for-its-investigative-intelligence-platform-and-new-deep-tech-extension/
https://tech.eu/brief/german-proptech-thing-it-collects-e4-2-million-to-expand-its-operating-system-for-smart-buildings/
https://tech.eu/brief/glue-raises-3-5-million-vr-collaboration-platform/
https://tech.eu/brief/snowplow-analytics-4-million-opensource-data-collection/
https://tech.eu/brief/israeli-proptech-startup-shapedo-gets-650000-from-goldacre-after-finishing-new-relab-accelerator-programme/
https://tech.eu/brief/eqt-ventures-closes-second-fund-at-e660-million-will-help-startups-scale-out-of-europe-and-us-companies-scale-in/
https://tech.eu/brief/siren-scores-10-million-series-a-for-its-investigative-intelligence-platform-and-new-deep-tech-extension/
https://tech.eu/brief/german-proptech-thing-it-collects-e4-2-million-to-expand-its-operating-system-for-smart-buildings/
https://tech.eu/brief/glue-raises-3-5-million-vr-collaboration-platform/
https://tec

In [121]:
getTechEUPosts()

['Wayve, a UK startup applying artificial intelligence to mobile robotics, $20 million Series A round led by Eclipse Ventures, with participation from Balderton Capital, existing investors and several undisclosed preeminent leaders in machine learning and robotics. to launch a pilot fleet of autonomous vehicles in central London; self-driving cars are the company’s first commercial application of its technology. The company wants to power mobile robotics through AI and machine learning, rather than sensors and hand-coded rules. Co-founder and CEO Amar Shah explained, “As computational power and data continue to grow, learning-based approaches will become more inevitable, especially for mobile robotics. The human brain has evolved over millions of years, computers have only had a few decades, but are catching up quickly.” \n\nWith this approach to autonomous vehicles, self-driving cars could better navigate unfamiliar and difficult roads. In fact, this past spring, Wayve tested a self-d

In [68]:
getContent()

'Bitmovin, the Austrian multimedia company that’s now headquartered in San Francisco, will receive up to €20 million in financing from the European Investment Bank (EIB). The loan is guaranteed by the Juncker Plan, under which the EIB and the European Commission are working together to boost the competitiveness of the European economy. Bitmovin powers world-leading video streaming services offered directly to viewers over the internet, also known as “over-the-top” (OTT) media services. Its global pool of customers include the BBC, fuboTV, Hulu Japan, RTL and iFlix. Previous investors include pan-European VCs such as Atomico, which led the 2016 Series A, and Highland Europe, which led the $30 million Series B in 2018. The financing will allow the company to strengthen its research and development and product development team in Austria and also support investments in sales and marketing to scale up its distribution network. Bitmovin CEO Stefan Lederer said: “We feel very honoured to rec

In [114]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk.probability import FreqDist
from collections import defaultdict
from string import punctuation
from heapq import nlargest
import nltk

def identifyTheme(posts):
    vectorizer = TfidfVectorizer(max_df =0.5, min_df=2, stop_words='english')
    # fit_transform method takes a list of string, and returns a 2D matrix. Each row represents a document/list item
    X = vectorizer.fit_transform(posts)
    km = KMeans(n_clusters = 3, init = 'k-means++', max_iter = 100, n_init=1, verbose=True)
    km.fit(X)
    text = {}
    for i,cluster in enumerate(km.labels_):
        oneDoc = posts[i]
        if cluster not in text.keys():
            text[cluster] = oneDoc
        else:
            text[cluster] += ' ' + oneDoc
    _stopwords = set(stopwords.words('english') + list(punctuation) + ['million','billion','year','millions','billions','\'s','\"','become','one','let'])
    
    # find 100 most important keywords from each cluster
    keywords = {}
    counts = {}
    for cluster in range(3):
        word_sent = word_tokenize(text[cluster].lower())
        word_sent = [word for word in word_sent if word not in _stopwords]
        freq = FreqDist(word_sent)
        keywords[cluster] = nlargest(100, freq, key=freq.get)
        counts[cluster]=freq
    
    # now find top keywords unique to each cluster
    unique_keys = {}
    for cluster in range(3):
        other_clusters = list(set(range(3)) - set([cluster]))
        keys_other_clusters = set(keywords[other_clusters[0]]).union(set(keywords[other_clusters[1]]))
        unique = set(keywords[cluster]) - keys_other_clusters
        unique_keys[cluster] = nlargest(10, unique, key=counts[cluster].get)
        
    print(unique_keys)

In [207]:
posts,links = getTechEUPosts()

In [208]:
identifyTheme(posts)

Initialization complete
Iteration  0, inertia 217.709
Iteration  1, inertia 112.044
Iteration  2, inertia 111.951
Converged at iteration 2: center shift 0.000000e+00 within tolerance 4.322579e-08
{0: ['mission', 'insurance', 'vc', '3d', 'access', 'percent', 'approach', 'video', 'women', 'app'], 1: ['ai', 'see', 'system', '–', 'venture', 'building', 'teams', 'real', 'connected', 'solutions'], 2: ['markets', 'lifi', 'provide', 'speys', 'way', 'debt', 'banking', 'programme', 'travel', 'open']}


In [209]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_df =0.5, min_df=2, stop_words='english')

In [210]:
# fit_transform method takes a list of string, and returns a 2D matrix. Each row represents a document/list item
X = vectorizer.fit_transform(posts)
X

<122x2168 sparse matrix of type '<class 'numpy.float64'>'
	with 12691 stored elements in Compressed Sparse Row format>

In [136]:
posts

['Wayve, a UK startup applying artificial intelligence to mobile robotics, $20 million Series A round led by Eclipse Ventures, with participation from Balderton Capital, existing investors and several undisclosed preeminent leaders in machine learning and robotics. to launch a pilot fleet of autonomous vehicles in central London; self-driving cars are the company’s first commercial application of its technology. The company wants to power mobile robotics through AI and machine learning, rather than sensors and hand-coded rules. Co-founder and CEO Amar Shah explained, “As computational power and data continue to grow, learning-based approaches will become more inevitable, especially for mobile robotics. The human brain has evolved over millions of years, computers have only had a few decades, but are catching up quickly.” \n\nWith this approach to autonomous vehicles, self-driving cars could better navigate unfamiliar and difficult roads. In fact, this past spring, Wayve tested a self-d

In [211]:
from sklearn.cluster import KMeans
km = KMeans(n_clusters = 3, init = 'k-means++', max_iter = 100, n_init=1, verbose=True)

In [212]:
km.fit(X)

Initialization complete
Iteration  0, inertia 214.924
Iteration  1, inertia 112.035
Converged at iteration 1: center shift 0.000000e+00 within tolerance 4.322579e-08


KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=100,
       n_clusters=3, n_init=1, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=True)

In [186]:
import numpy as np
np.unique(km.labels_, return_counts=True)


(array([0, 1, 2], dtype=int32), array([22, 31, 80]))

In [187]:

text = {}
for i,cluster in enumerate(km.labels_):
    oneDoc = posts[i]
    if cluster not in text.keys():
        text[cluster] = oneDoc
    else:
        text[cluster] += " " + oneDoc


In [188]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk.probability import FreqDist
from collections import defaultdict
from string import punctuation
from heapq import nlargest
import nltk

In [189]:
_stopwords = set(stopwords.words('english') + list(punctuation) + ['million','billion','year','millions','billions','\'s','\"','become','one','let'])

In [190]:
# find 100 most important keywords from each cluster
keywords = {}
counts = {}
for cluster in range(3):
    word_sent = word_tokenize(text[cluster].lower())
    word_sent = [word for word in word_sent if word not in _stopwords]
    freq = FreqDist(word_sent)
    keywords[cluster] = nlargest(100, freq, key=freq.get)
    counts[cluster]=freq

In [191]:
# now find top keywords unique to each cluster
unique_keys = {}
for cluster in range(3):
    other_clusters = list(set(range(3)) - set([cluster]))
    keys_other_clusters = set(keywords[other_clusters[0]]).union(set(keywords[other_clusters[1]]))
    unique = set(keywords[cluster]) - keys_other_clusters
    unique_keys[cluster] = nlargest(10, unique, key=counts[cluster].get)

In [192]:
unique_keys

{0: ['people',
  'insurance',
  'experiences',
  'home',
  'online',
  'jeff',
  'brands',
  'access',
  'sales',
  'search'],
 1: ['firm',
  'startups',
  '🎧',
  'podcast',
  'vc',
  'entrepreneurs',
  'tech.eu',
  'interview',
  'venture',
  'andrii'],
 2: ['data',
  'software',
  'management',
  'businesses',
  'ai',
  'group',
  'well',
  'financial',
  'solutions',
  'potential']}

In [144]:
def getTextFromBBCNews(url):
    soup = getBSoup(url)
    article = soup.find('div',class_='story-body__inner').find_all('p')
    article = ' '.join(map(lambda p: p.text, article)).replace('\\','').replace('\"','').replace('\'','')
    return article


In [193]:
article = getTextFromBBCNews('https://www.bbc.co.uk/news/technology-50418357')

In [194]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=10)
classifier.fit(X, km.labels_)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [195]:
test = vectorizer.transform([article])

In [196]:
test

<1x2254 sparse matrix of type '<class 'numpy.float64'>'
	with 187 stored elements in Compressed Sparse Row format>

In [197]:
classifier.predict(test)

array([2], dtype=int32)

In [198]:
val = classifier.predict(test)

In [199]:
print(val[0])

2


In [200]:
article = getTextFromBBCNews('https://www.bbc.co.uk/news/technology-50316951')
classifier = KNeighborsClassifier(n_neighbors=10)
classifier.fit(X, km.labels_)
test = vectorizer.transform([article])
val2 = classifier.predict(test)
val2

array([0], dtype=int32)

In [201]:
print(val2[0])


0


In [203]:
article = getTextFromBBCNews('https://www.bbc.co.uk/news/technology-50418357')
test = vectorizer.transform([article])
val2 = classifier.predict(test)
val2

array([2], dtype=int32)

In [176]:
km.labels_

array([1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 2, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 2,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 2, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 0],
      dtype=int32)

In [178]:
posts[0]

'Wayve, a UK startup applying artificial intelligence to mobile robotics, $20 million Series A round led by Eclipse Ventures, with participation from Balderton Capital, existing investors and several undisclosed preeminent leaders in machine learning and robotics. to launch a pilot fleet of autonomous vehicles in central London; self-driving cars are the company’s first commercial application of its technology. The company wants to power mobile robotics through AI and machine learning, rather than sensors and hand-coded rules. Co-founder and CEO Amar Shah explained, “As computational power and data continue to grow, learning-based approaches will become more inevitable, especially for mobile robotics. The human brain has evolved over millions of years, computers have only had a few decades, but are catching up quickly.” \n\nWith this approach to autonomous vehicles, self-driving cars could better navigate unfamiliar and difficult roads. In fact, this past spring, Wayve tested a self-dr